services:
  ####################### DATABASE SETUP #######################
  db:
    container_name: db
    image: postgres:15.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db:/var/lib/postgresql/data

  migration:
    container_name: db-migration
    build:
      context: ../.
      dockerfile: fhevm-engine/fhevm-db/Dockerfile
      tags:
      - "fhevm-db-migration:v0.7.0-local"
    image: ghcr.io/zama-ai/fhevm-db-migration:v0.7.0-rc0
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TENANT_API_KEY: ${TENANT_API_KEY}
      ACL_CONTRACT_ADDRESS: ${ACL_CONTRACT_ADDRESS}
      INPUT_VERIFIER_ADDRESS: ${INPUT_VERIFIER_ADDRESS}
    volumes:
      - ../fhevm-engine/fhevm-keys:/fhevm-keys
    depends_on:
      db:
        condition: service_healthy

  ####################### COPROCESSOR SERVICES #######################
  coprocessor:
    container_name: coprocessor
    build:
      context: ../.
      dockerfile: fhevm-engine/coprocessor/Dockerfile
      tags:
        - "ghcr.io/zama-ai/fhevm-coprocessor:v0.7.0-local"
    image: ghcr.io/zama-ai/fhevm-coprocessor:v0.7.0-rc0
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '50051:50051'
    volumes:
      - ./config/coprocessor.key:/usr/share/coprocessor.key
    command:
      - coprocessor
      - --run-server
      - --server-addr=0.0.0.0:50051
      - --coprocessor-private-key=/usr/share/coprocessor.key
    depends_on:
      migration:
        condition: service_completed_successfully

  fhevm-listener:
    container_name: "fhevm-listener"
    build:
      context: ../.
      dockerfile: fhevm-engine/coprocessor/Dockerfile
      tags:
        - "ghcr.io/zama-ai/fhevm-coprocessor:v0.7.0-local"
    image: ghcr.io/zama-ai/fhevm-coprocessor:b826fbf
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TENANT_API_KEY: ${TENANT_API_KEY}
    ports:
      - '50052:50052'
    command:
      - fhevm_listener
      - --database-url=$DATABASE_URL
      - --coprocessor-api-key=$TENANT_API_KEY
      - --url=ws://layer1-node:8545
    depends_on:
      migration:
        condition: service_completed_successfully

  transaction-sender:
    container_name: "transaction-sender"
    build:
      context: ../.
      dockerfile: fhevm-engine/coprocessor/Dockerfile
      tags:
        - "ghcr.io/zama-ai/fhevm-coprocessor:v0.7.0-local"
    # image: ghcr.io/zama-ai/fhevm-coprocessor:a741a94
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '50053:50053'
    command:
      - transaction_sender
      - --zkpok-manager-address=0x812b06e1CDCE800494b79fFE4f925A504a9A9810
      - --ciphertext-storage-address=0x5ffdaAB0373E62E2ea2944776209aEf29E631A64
      - --gateway-url=http://layer2-node:8546
      - --private-key=0x8f82b3f482c19a95ac29c82cf048c076ed0de2530c64a73f2d2d7d1e64b5cc6e # account[5] - layer2
      - --database-url=${DATABASE_URL}
    depends_on:
      migration:
        condition: service_completed_successfully

  # gw-listener:
  #   container_name: "gw-listener"
  #   build:
  #     context: ../.
  #     dockerfile: fhevm-engine/coprocessor/Dockerfile
  #     tags:
  #       - "ghcr.io/zama-ai/fhevm-coprocessor:v0.7.0-local"
  #   image: ghcr.io/zama-ai/fhevm-coprocessor:b826fbf
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     TENANT_API_KEY: ${TENANT_API_KEY}
  #   ports:
  #     - '50054:50054'
  #   command:
  #     - gw_listener
  #   depends_on:
  #     migration:
  #       condition: service_completed_successfully

  # zkproof-worker:
  #   container_name: "zkproof-worker"
  #   build:
  #     context: ../.
  #     dockerfile: fhevm-engine/coprocessor/Dockerfile
  #     tags:
  #       - "ghcr.io/zama-ai/fhevm-coprocessor:v0.7.0-local"
  #   image: ghcr.io/zama-ai/fhevm-coprocessor:b826fbf
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     TENANT_API_KEY: ${TENANT_API_KEY}
  #   ports:
  #     - '50055:50055'
  #   command:
  #     - zkproof_worker
  #   depends_on:
  #     migration:
  #       condition: service_completed_successfully

  # # sns-worker is on standby untill next release
  # sns-worker:
  #   container_name: "sns-worker"
  #   build:
  #     context: ../.
  #     dockerfile: fhevm-engine/coprocessor/Dockerfile
  #     tags:
  #       - "ghcr.io/zama-ai/fhevm-coprocessor:v0.7.0-local"
  #   image: ghcr.io/zama-ai/fhevm-coprocessor:0f21ac4
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@db:5432/coprocessor
  #   command:
  #     - sns_worker
  #     - --tenant-id=1
  #     - --pg-listen-channel="event_pbs_new_work"
  #     - --pg-notify-channel="event_pbs_computed"
  #   ports:
  #    - '50053:50053'
  #   depends_on:
  #     migration:
  #       condition: service_completed_successfully

volumes:
  db:
