services:
  layer2-node:
    container_name: layer2-node
    image: ghcr.io/foundry-rs/foundry:stable
    environment:
      MNEMONIC: ${MNEMONIC}
    entrypoint:
      [
        "anvil",
        "--block-time",
        "0.1",
        "--host",
        "0.0.0.0",
        "--port",
        "8546",
        "--chain-id",
        "54321",
        "--accounts",
        "15",
        "--mnemonic",
        "${MNEMONIC}"
      ]
    ports:
      - "8546:8546"
  
  layer2-sc-deploy:
    container_name: layer2-sc-deploy
    image: ghcr.io/zama-ai/gateway-l2/sc-bundle:b479cf8
    volumes:
      - ./config/.env.staging.layer2:/app/.env
    entrypoint: ["/app/launch-staging-gateway-layer2.sh"]
