services:
  layer1-node:
    container_name: layer1-node
    image: ghcr.io/foundry-rs/foundry:stable
    environment:
      MNEMONIC: ${MNEMONIC}
    entrypoint:
      [
        "anvil",
        "--block-time",
        "0.1",
        "--host",
        "0.0.0.0",
        "--port",
        "8545",
        "--chain-id",
        "12345",
        "--accounts",
        "15",
        "--mnemonic",
        "${MNEMONIC}",
      ]
    ports:
      - "8545:8545"
  
  layer1-sc-deploy:
    container_name: layer1-sc-deploy
    image: ghcr.io/zama-ai/fhevm-smart-contracts-dev:82fb642
    volumes:
      - ./config/.env.staging.layer1:/app/.env
    entrypoint: ["/app/launch-fhevm-staging.sh"]
