name: Pull request tests (contracts)

on:
  pull_request:
    branches:
      - "*"
    paths:
      - contracts/**

jobs:
  build:
    runs-on: large_ubuntu_32
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # v1.3.1
        with:
          version: stable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp ./contracts/.env.example ./contracts/.env
      - run: npm --prefix ./contracts ci --include=optional
      - name: Prettier check
        run: npm --prefix ./contracts run prettier:check
      - name: "Run JS/TS tests"
        run: npm --prefix ./contracts run test:mock
      - name: "Run forge tests"
        run: "cd contracts && forge test"
