name: fhevm

services:
  db:
    container_name: db
    image: postgres:15.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db:/var/lib/postgresql/data

  migration:
      container_name: migration
      image: migration:v1
      environment:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/coprocessor
      depends_on:
        db:
          condition: service_healthy

  coprocessor:
    container_name: coprocessor
    image: ghcr.io/zama-ai/fhevm-coprocessor:v0.1.0-3
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/coprocessor
    ports:
      - '50051:50051'
    volumes:
      - ./coprocessor.key:/usr/share/coprocessor.key
    command:
      - --run-bg-worker
      - --run-server
      - --server-addr=0.0.0.0:50051
      - --coprocessor-private-key=/usr/share/coprocessor.key
    depends_on:
      migration:
        condition: service_completed_successfully

  geth:
    container_name: geth
    image: ghcr.io/zama-ai/geth-coprocessor-devnode:v8
    environment:
      FHEVM_COPROCESSOR_API_KEY: a1503fb6-d79b-4e9e-826d-44cf262f3e05
      FHEVM_COPROCESSOR_URL: coprocessor:50051
      COPROCESSOR_CONTRACT_ADDRESS: 0x6819e3aDc437fAf9D533490eD3a7552493fCE3B1
      ACL_CONTRACT_ADDRESS: 0x339EcE85B9E11a3A3AA557582784a15d7F82AAf2
    volumes:
      - ./geth:/geth
    ports:
      - '8745:8545'
    depends_on:
      coprocessor:
        condition: service_started

volumes:
  db:
    driver: local
