name: fhevm

services:
  db:
    container_name: db
    image: postgres:15.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db:/var/lib/postgresql/data

  migration:
      container_name: db-migration
      build:
        context: ../../.
        dockerfile: fhevm-engine/fhevm-db/Dockerfile
        tags:
        - "fhevm-db-migration:v0.7.0-local"
      image: fhevm-db-migration:v0.7.0-local
      environment:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/coprocessor
        TENANT_API_KEY: "a1503fb6-d79b-4e9e-826d-44cf262f3e05"
        ACL_CONTRACT_ADDRESS: "0x339EcE85B9E11a3A3AA557582784a15d7F82AAf2"
        INPUT_VERIFIER_ADDRESS: "0x69dE3158643e738a0724418b21a35FAA20CBb1c5"
      volumes:
        - ../fhevm-keys:/fhevm-keys
      depends_on:
        db:
          condition: service_healthy

  coprocessor:
    container_name: coprocessor
    build:
      context: ../../.
      dockerfile: fhevm-engine/coprocessor/Dockerfile
      tags:
        - "fhevm-coprocessor:v0.7.0-local"
    image: fhevm-coprocessor:v0.7.0-local
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/coprocessor
    ports:
      - '50051:50051'
    volumes:
      - ./coprocessor.key:/usr/share/coprocessor.key
    command:
      - --run-bg-worker
      - --run-server
      - --server-addr=0.0.0.0:50051
      - --coprocessor-private-key=/usr/share/coprocessor.key
    depends_on:
      migration:
        condition: service_completed_successfully

  geth:
    container_name: geth
    image: ethereum/client-go:v1.15.0
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - geth-data:/root/.ethereum
    command:
      # Sync configuration
      - --syncmode=snap
      - --nodiscover
      # HTTP configuration
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3
      - --http.corsdomain=*
      - --http.vhosts=*
      # WebSocket configuration
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=eth,net,web3
      - --ws.origins=*
      # Performance & security
      - --cache=1024
      - --rpc.allow-unprotected-txs
      - --txlookuplimit=0
    healthcheck:
      test: ["CMD", "geth", "attach", "http://localhost:8545", "--exec", "eth.blockNumber"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db:
  geth-data: