services:
  db:
    image: postgres:15.7
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - common-network

  coproc:
    image: ghcr.io/zama-ai/fhevm-coprocessor:v9
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/coprocessor
    ports:
      - '50055:50052'
    volumes:
      - ${PWD}/coprocessor.key:/usr/share/coprocessor.key
    command:
      - --run-bg-worker
      - --run-server
      - --server-addr=0.0.0.0:50052
      - --coprocessor-private-key=/usr/share/coprocessor.key
    networks:
      - common-network

  geth:
    image: ghcr.io/zama-ai/geth-coprocessor-devnode:v5
    environment:
      - FHEVM_COPROCESSOR_API_KEY=a1503fb6-d79b-4e9e-826d-44cf262f3e05
      - FHEVM_COPROCESSOR_URL=coproc:50052
      - COPROCESSOR_CONTRACT_ADDRESS=0xcCAe95fF1d11656358E782570dF0418F59fA40e1
    volumes:
      - ${PWD}/scripts/run.sh:/entrypoint.sh
    ports:
      - '8745:8545'
      - '8746:8546'
    networks:
      - common-network

volumes:
  db:
    driver: local

networks:
  common-network:
    driver: bridge
    external: true
