[package]
name = "test-harness"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# workspace dependencies
alloy = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
rand = { workspace = true}
serde_json = { workspace = true }
sqlx = { workspace = true}
testcontainers = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true}
tracing = { workspace = true }

# local dependencies
fhevm-engine-common = { path = "../fhevm-engine-common" }

[features]
gpu = []
