[backend.hyperstack.single-h100]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R535 CUDA 12.2"
flavor_name = "n3-H100x1"
user = "ubuntu"

[backend.hyperstack.l40]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R535 CUDA 12.2"
flavor_name = "n3-L40x1"
user = "ubuntu"
