import { FheType } from './common';

/**
 * A constant array containing all Fully Homomorphic Encryption (FHE) types.
 * Each type is represented as an object with the following properties:
 *
 * - `type`: The name of the FHE type.
 * - `value`: A unique numeric identifier for the FHE type.
 * - `supportedOperators`: An array of strings representing the operators supported by the FHE type.
 * - `bitLength`: The bit length of the FHE type.
 * - `clearMatchingType`: The corresponding clear (non-encrypted) type in Solidity.
 *
 * The FHE types included are:
 *
 * - `Ebool`: Boolean type with a bit length of 1.
 * - `Euint4`: Unsigned integer type with a bit length of 4.
 * - `Euint8`: Unsigned integer type with a bit length of 8.
 * - `Euint16`: Unsigned integer type with a bit length of 16.
 * - `Euint32`: Unsigned integer type with a bit length of 32.
 * - `Euint64`: Unsigned integer type with a bit length of 64.
 * - `Euint128`: Unsigned integer type with a bit length of 128.
 * - `Euint160`: Unsigned integer type with a bit length of 160.
 * - `Euint256`: Unsigned integer type with a bit length of 256.
 * - `Ebytes64`: Byte array type with a bit length of 512.
 * - `Ebytes128`: Byte array type with a bit length of 1024.
 * - `Ebytes256`: Byte array type with a bit length of 2048.
 */
export const ALL_FHE_TYPES: FheType[] = [
  {
    type: 'Ebool',
    value: 0,
    supportedOperators: ['and', 'or', 'xor', 'eq', 'ne', 'not', 'select', 'rand'],
    bitLength: 1, // 8 bits?
    clearMatchingType: 'bool',
  },
  {
    type: 'Euint4',
    value: 1,
    supportedOperators: [],
    bitLength: 4,
    clearMatchingType: 'uint8',
  },
  {
    type: 'Euint8',
    value: 2,
    supportedOperators: [
      'add',
      'sub',
      'mul',
      'div',
      'rem',
      'and',
      'or',
      'xor',
      'shl',
      'shr',
      'rotl',
      'rotr',
      'eq',
      'ne',
      'ge',
      'gt',
      'le',
      'lt',
      'min',
      'max',
      'neg',
      'not',
      'select',
      'rand',
    ],
    bitLength: 8,
    clearMatchingType: 'uint8',
  },
  {
    type: 'Euint16',
    value: 3,
    supportedOperators: [
      'add',
      'sub',
      'mul',
      'div',
      'rem',
      'and',
      'or',
      'xor',
      'shl',
      'shr',
      'rotl',
      'rotr',
      'eq',
      'ne',
      'ge',
      'gt',
      'le',
      'lt',
      'min',
      'max',
      'neg',
      'not',
      'select',
      'rand',
      'randBounded',
    ],
    bitLength: 16,
    clearMatchingType: 'uint16',
  },
  {
    type: 'Euint32',
    value: 4,
    supportedOperators: [
      'add',
      'sub',
      'mul',
      'div',
      'rem',
      'and',
      'or',
      'xor',
      'shl',
      'shr',
      'rotl',
      'rotr',
      'eq',
      'ne',
      'ge',
      'gt',
      'le',
      'lt',
      'min',
      'max',
      'neg',
      'not',
      'select',
      'rand',
      'randBounded',
    ],
    bitLength: 32,
    clearMatchingType: 'uint32',
  },
  {
    type: 'Euint64',
    value: 5,
    supportedOperators: [
      'add',
      'sub',
      'mul',
      'div',
      'rem',
      'and',
      'or',
      'xor',
      'shl',
      'shr',
      'rotl',
      'rotr',
      'eq',
      'ne',
      'ge',
      'gt',
      'le',
      'lt',
      'min',
      'max',
      'neg',
      'not',
      'select',
      'rand',
      'randBounded',
    ],
    bitLength: 64,
    clearMatchingType: 'uint64',
  },
  {
    type: 'Euint128',
    value: 6,
    supportedOperators: [
      'add',
      'sub',
      'mul',
      'div',
      'rem',
      'and',
      'or',
      'xor',
      'shl',
      'shr',
      'rotl',
      'rotr',
      'eq',
      'ne',
      'ge',
      'gt',
      'le',
      'lt',
      'min',
      'max',
      'neg',
      'not',
      'select',
      'rand',
      'randBounded',
    ],
    bitLength: 128,
    clearMatchingType: 'uint128',
  },
  {
    type: 'Euint160',
    value: 7,
    supportedOperators: [],
    bitLength: 160,
    clearMatchingType: 'uint160',
  },
  {
    type: 'Euint256',
    value: 8,
    supportedOperators: ['neg', 'not', 'select', 'rand', 'randBounded'],
    bitLength: 256,
    clearMatchingType: 'uint256',
  },
  {
    type: 'Ebytes64',
    value: 9,
    supportedOperators: ['eq', 'ne', 'select', 'rand'],
    bitLength: 512,
    clearMatchingType: 'bytes memory',
  },
  {
    type: 'Ebytes128',
    value: 10,
    supportedOperators: ['eq', 'ne', 'select', 'rand'],
    bitLength: 1024,
    clearMatchingType: 'bytes memory',
  },
  {
    type: 'Ebytes256',
    value: 11,
    supportedOperators: ['eq', 'ne', 'select', 'rand'],
    bitLength: 2048,
    clearMatchingType: 'bytes memory',
  },
  {
    type: 'Eaddress',
    isAlias: true,
    aliasType: 'Euint160',
    supportedOperators: ['eq', 'ne', 'select'],
    bitLength: 160,
    clearMatchingType: 'address',
    clearMatchingTypeAlias: 'uint160',
  },
];
