[workspace]
resolver = "2"
members = ["coprocessor", "executor", "fhevm-engine-common"]

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
prost = "0.13"
tonic = { version = "0.12", features = ["server"] }
bincode = "1.3.3"
sha3 = "0.10.8"
anyhow = "1.0.86"
daggy = "0.8.0"

[profile.dev.package.tfhe]
overflow-checks = false

# for testing in release mode due to too big
# binary inside mac
[profile.release]
opt-level = "z"
lto = "fat"
