name: Build and Push Docker Image

on:
  push:
    branches:
      - docker_release
  workflow_dispatch:
    inputs:
      image_name:
        description: 'The full name of the Docker image (e.g., ghcr.io/zama-ai/fhevm-coprocessor)'
        required: true
        default: "ghcr.io/zama-ai/fhevm-coprocessor"
        type: string
      dockerfile_path:
        description: 'Path to the Dockerfile (default: ./fhevm-engine/coprocessor/Dockerfile)'
        required: true
        default: './fhevm-engine/coprocessor/Dockerfile'
        type: string

env:
  DOCKER_REGISTRY: ghcr.io/zama-ai
  DOCKER_IMAGE_NAME: fhevm-coprocessor
  DOCKERFILE_PATH: "./fhevm-engine/coprocessor/Dockerfile"

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Get Docker tag
        id: get_tag
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            DOCKER_IMAGE_TAG="${GITHUB_REF#refs/tags/}"
          else
            DOCKER_IMAGE_TAG="${GITHUB_SHA}"
          fi
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: ${{ matrix.platforms }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
        strategy:
          matrix:
            platforms: [linux/amd64]
