name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cargo-tests:
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.82.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
      with:
        toolchain: ${{ matrix.rust }}
        cache: true
        cache-on-failure: true
        cache-workspaces: target
        cache-directories: |
          ~/.cargo/registry
          ~/.cargo/git
        components: protobuf-compiler, sqlx-cli

    # - name: Install protobuf-compiler
    #   run: |
    #     sudo apt-get install -y protobuf-compiler && \
    #     cargo install sqlx-cli

    - name: Init database
      run: make init_db
      working-directory: fhevm-engine/coprocessor

    - name: Run tests
      run: |
        DATABASE_URL=postgresql://postgres:postgres@localhost:5432/coprocessor cargo test --release -- --test-threads=1
      working-directory: fhevm-engine
