name: "fhEVM Coprocessor Docker Image"

on:
  push:
    branches:
      - main
      - amina/fhevm-coprocessor-workflows
    paths:
      - .github/workflows/fhevm-coprocessor.yml
      - .github/workflows/common-docker.yml
      - fhevm-engine/coprocessor/**
  release:
    types:
      - published

concurrency:
  group: fhevm-coprocessor
  cancel-in-progress: true

jobs:
  docker-coprocessor:
    uses: ./.github/workflows/common-docker.yml
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      working-directory: "."
      push_image: ${{ github.event_name == 'release' || github.ref_name == 'main' }}
      image-name: "fhevm-coprocessor"
      generate-dev-image: false
      docker-file: "fhevm-engine/coprocessor/Dockerfile"
      arm-build: true

    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

  done:
    runs-on: ubuntu-latest
    name: Pipeline Done
    steps:
      - name: Success
        run: echo Pipeline Done
    needs:
      - docker-coprocessor
