name: Fhevm Host Contracts Slither Analysis

on:
  pull_request:
    branches:
      - main
jobs:
  check-changes:
    permissions:
      actions: 'read'
      contents: 'read'
      pull-requests: 'read'
    runs-on: ubuntu-latest
    outputs:
      changes-contracts-files: ${{ steps.filter.outputs.contracts-files }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        id: filter
        with:
          filters: |
            contracts-files:
              - .github/workflows/host-contracts-slither-analysis.yml
              - contracts/**
  analyze:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.changes-contracts-files == 'true' }}
    runs-on: large_ubuntu_32
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
      - run: cp ./contracts/.env.example ./contracts/.env
      - run: npm --prefix ./contracts ci --include=optional
      - run: npm --prefix ./contracts install
      - run: npm --prefix ./contracts run compile
      - name: Run Slither
        uses: crytic/slither-action@d86660fe7e45835a0ec7b7aeb768d271fb421ea0 # temporarily commit that fixes the issue
        with:
          node-version: 20
          ignore-compile: false
          solc-version: "0.8.24"
          slither-config: ".slither.config.json"
          sarif: results.sarif
          fail-on: none
          target: "./contracts/"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 # v3.28.11
        with:
          sarif_file: results.sarif

permissions:
  contents: read
  checks: write