name: Slither Analysis

on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: cp ./contracts/.env.example ./contracts/.env
      - run: npm --prefix ./contracts ci --include=optional
      - run: npm --prefix ./contracts install
      - run: npm --prefix ./contracts run compile
      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        with:
          node-version: 20
          ignore-compile: false
          solc-version: "0.8.24"
          slither-config: "contracts/.slither.config.json"
          sarif: results.sarif
          fail-on: none
