name: Slither Analysis
permissions:
  contents: read
  checks: write
on:
  pull_request:
    branches:
      - main
    paths:
      - contracts/**
      - .github/workflows/slither.yml
jobs:
  analyze:
    runs-on: large_ubuntu_32
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: cp ./contracts/.env.example ./contracts/.env
      - run: npm --prefix ./contracts ci --include=optional
      - run: npm --prefix ./contracts install
      - run: npm --prefix ./contracts run compile
      - name: Run Slither
        uses: crytic/slither-action@d86660fe7e45835a0ec7b7aeb768d271fb421ea0 # temporarily commit that fixes the issue
        with:
          node-version: 20
          ignore-compile: false
          solc-version: "0.8.24"
          slither-config: ".slither.config.json"
          sarif: results.sarif
          fail-on: none
          target: "./contracts/"
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@80f993039571a6de66594ecaa432875a6942e8e0 #v2.20.6
        with:
          sarif_file: results.sarif
