name: Pull request tests (contracts)

on:
  pull_request:
    branches:
      - "*"
    paths:
      - contracts/**

jobs:
  build:
    runs-on: large_ubuntu_32
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: stable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp ./contracts/.env.example ./contracts/.env
      - run: npm --prefix ./contracts ci --include=optional
      - name: Prettier check
        run: npm --prefix ./contracts run prettier:check
      - name: "Run JS/TS tests"
        run: npm --prefix ./contracts run test:mock
      - name: "Run forge tests"
        run: "cd contracts && forge test"
